repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: python
        types: [python]
        require_serial: true
        additional_dependencies: ["pylint==4.0.4"]
        args: ["--disable=R,C,W,E0401"]
