executors:
  local: 
    type: LocalExecutor
  joblib:
    type: JoblibExecutor
  dask:
    type: DaskExecutor
    LocalCluster_config:
      name: 'es-dask_cluster'
      n_workers: 2
      threads_per_worker: 1
samplers:
  random_kill:
    type: RandomSamplerWithKill
    bounds: [[-5, 5], [0, 1]]
    budget: 50
    batch_size: 10
    parameters: ['c1', 'c2']
    kill_after: 4
runners:
  r1: 
    type: ExampleRunner
supervisor:
  base_run_dir: tmp_path
  run_mode: fresh
  run_order:
  - executor: local
    sampler: random_kill
    runner : r1