sampler:
  type: ActiveLearningStaticPoolSampler
  bounds: 
    - [1, 3]
    - [1, 3]
  parameters: ["m", "n"]
  init_num_samples: 5000
  aquisition_batch_size: 512
  total_budget: 80000
  selection_method: random
  base_kernel: linear
  parser_kwargs: 
    type: 'STATICPOOLparser'
    data_path: '/scratch/project_2007159/cursed-tglf/qualikiz/train_data_raw.pkl'
    inputs: 
      - 'ane'
      - 'ate'
      - 'autor'
      - 'machtor'
      - 'x'
      - 'zeff'
      - 'gammae'
      - 'q'
      - 'smag'
      - 'alpha'
      - 'ani1'
      - 'ati0'
      - 'normni1'
      - 'ti_te0'
      - 'lognustar'
    target: 
      - 'efiitg_gb'
    data_args: 
      train_size: 0.01
      valid_size: 0.01
      test_size: 0.01
  model_kwargs:
    model_width: 512
    model_depth: 4
    dropout: 0.0
  train_kwargs:
    stuff: stuff 

  # kernel_transform: [('rp', [512])]

runner:
  type: STATICPOOLrunner
  executable_path: None
  other_params: {}

executor:
  type: LocalDaskExecutor
  base_run_dir: qlkn_test_run/
  worker_args:
    account: project_2009007
    queue: medium
    cores: 4
    memory: 1GB
    processes: 1
    walltime: '03:10:00'
    interface: ib0
    job_script_prologue:
      - export PYTHONPATH=$PYTHONPATH:/src

  num_workers: 4