sampler:
  type: ActiveLearningBMDALStaticPoolSampler
  num_initial_points: 512
  aquisition_batch_size: 512
  total_budget: 2000
  selection_method: random
  base_kernel: linear
  parser_kwargs: 
    type: 'STATICPOOLparser'
    data_path: '/scratch/project_2007159/cursed-tglf/qualikiz/train_data_raw.pkl'
    inputs: 
      - 'ane'
      - 'ate'
      - 'autor'
      - 'machtor'
      - 'x'
      - 'zeff'
      - 'gammae'
      - 'q'
      - 'smag'
      - 'alpha'
      - 'ani1'
      - 'ati0'
      - 'normni1'
      - 'ti_te0'
      - 'lognustar'
    target: 
      - 'efiitg_gb'
    data_args: 
      train_size: 0.01
      valid_size: 0.01
      test_size: 0.01
  model_kwargs:
    model_width: 512
    model_depth: 4
    dropout: 0.0
  train_kwargs:
    stuff: stuff 

  # kernel_transform: [('rp', [512])]

runner:
  type: STATICPOOLrunner
  executable_path: None
  other_params: {}

executor:
  type: DaskExecutor
  base_run_dir: data_store/qlkn_test_run_random/
  worker_args: 
    local: 1
