sampler:
  type: ActiveLearningStaticPoolSampler
  num_initial_points: 5000
  aquisition_batch_size: 512
  total_budget: 12000
  selection_method: random
  base_kernel: linear
  parser_kwargs: 
    type: 'STATICPOOLparser'
    data_path: '/scratch/project_2007159/cursed-tglf/qualikiz/train_data_raw.pkl'
    inputs: 
      - 'ane'
      - 'ate'
      - 'autor'
      - 'machtor'
      - 'x'
      - 'zeff'
      - 'gammae'
      - 'q'
      - 'smag'
      - 'alpha'
      - 'ani1'
      - 'ati0'
      - 'normni1'
      - 'ti_te0'
      - 'lognustar'
    target: 
      - 'efiitg_gb'
    data_args: 
      train_size: 0.01
      valid_size: 0.01
      test_size: 0.01
  model_kwargs:
    model_width: 512
    model_depth: 4
    dropout: 0.0
  train_kwargs:
    stuff: stuff 

  # kernel_transform: [('rp', [512])]

runner:
  type: STATICPOOLrunner
  executable_path: None
  other_params: {}

executor:
  type: DaskExecutor
  base_run_dir: data_store/qlkn_test_cpugpurun/
  worker_args:
    simulator_workers: 1
    surrogate_workers: 1
    simulator_args: 
      account: project_2007159
      queue: medium
      cores: 8
      memory: 4GB
      processes: 1
      walltime: '08:00:00'
      interface: ib0
      job_extra_directives: 
        - '--job-name=SIMULATOR'
      job_script_prologue:
        - module load python-data 
        - source /scratch/project_2007159/cursed-tglf/.venv/bin/activate
        - export PYTHONPATH=$PYTHONPATH:/scratch/project_2007159/cursed-tglf/src:/scratch/project_2007159/cursed-tglf/src/samplers/bmdal
    surrogate_args: 
      account: project_2007159
      queue: gpusmall 
      cores: 10
      memory: 4GB
      processes: 1
      walltime: '02:00:00'
      interface: ib0
      job_extra_directives: 
        - '--job-name=SURROGATE'
        - '--gres=gpu:a100:1'
      job_script_prologue:
        - module load python-data 
        - source /scratch/project_2007159/cursed-tglf/.venv/bin/activate
        - export PYTHONPATH=$PYTHONPATH:/scratch/project_2007159/cursed-tglf/src:/scratch/project_2007159/cursed-tglf/src/samplers/bmdal
  
