sampler:
  type: Grid
  bounds: [[1.0e-5, 1.0e-4], [2.0, 2.0], [2.0, 2.0], [1.0, 1.0], [10.0,10.0]]
  num_samples: [2, 1, 1, 1, 1]
  parameters: ['dBB', 'alpha', 'beta', 'V_loop_wall', 'tau_V_loop']

runner:
  type: DREAMrunner
  executable_path: "/scratch/project_2004389/aarojarvinen/DREAM_OCT_2024/build/iface/dreami"
  other_params: {
    "base_input_file_path": "/scratch/project_2004389/aarojarvinen/JET_95135/DREAM_es_test/dream_input.h5",
    "only_generate_files": False,
    "soft": {
      "run_soft": True,
      "type": SOFTrunner,
      "executable_path": "/scratch/project_2004389/aarojarvinen/SOFT2/build/src/soft",
      "other_params": {
        "only_generate_files": False,
        "time_idx": ["20", "47"],
        "mag_field_path": ["/scratch/project_2004389/aarojarvinen/JET_95135/cont_simulation_short_radialdBB/mag_fields/Mag_field_SOFT_2_JET_95135_48.08.h5", "/scratch/project_2004389/aarojarvinen/JET_95135/cont_simulation_short_radialdBB/mag_fields/Mag_field_SOFT_2_JET_95135_48.08.h5"],
        "number_of_mpi": 1,
      }
    }
   }

executor:
  type: DaskExecutor
  base_run_dir: /scratch/project_2004389/aarojarvinen/JET_95135/DREAM_es_test
  worker_args: 
    local: 'True'
    secondary_SLURM: 'True'
    adapt: 'True'
    slurm_args:
      account: "project_2004389"
      queue: "small"
      cores: 32 
      memory: "32GB"
      processes: 1
      walltime: "24:00:00" 
      interface: "ib0"
      local_directory: "SLURMlog"
      job_script_prologue: 
        - 'export OMP_NUM_THREADS=32'
        - 'module load python-data'
        - 'module load gsl'
        - 'module load hdf5'
        - 'source /scratch/project_2004389/aarojarvinen/env/bin/activate'
        - 'export PYTHONPATH=$PYTHONPATH:/scratch/project_2004389/aarojarvinen/enchanted-surrogates/src' 
        - 'cd /scratch/project_2004389/aarojarvinen/enchanted-surrogates'
    num_workers: 2
