executors:
  ex1:
    type: LocalExecutor
  ex2:
    type: LocalExecutor
samplers:
  samp1:
    type: RandomSampler
    bounds: [[0.0, 1.0], [0.0, 10.0]]
    budget: 4
    parameters: ['c1', 'c2']
  samp2:
    type: RandomSampler
    bounds: [[0.0, 1.0], [0.0, 10.0]]
    budget: 4
    parameters: ['c1', 'c2']
runners:
  runner1:
    type: ExampleRunner
    other_params: {}

supervisor:
  base_run_dir: "data_dir/local"
  run_order:
  - executor: ex1
    sampler: samp1
    runner: runner1
  - executor: ex1
    sampler: samp2
    runner: runner1

# ONLY ONE --------------------
#
#executors:
#  ex1:
#    type: LocalExecutor
#samplers:
#  samp1:
#    type: RandomSampler
#    bounds: [[0.0, 1.0], [0.0, 10.0]]
#    budget: 4
#    parameters: ['c1', 'c2']
#runners:
#  runner1:
#    type: ExampleRunner
#    other_params: {}
#
#supervisor:
#  base_run_dir: "data_dir/local"
#  run_order:
#  - group1:
#      executor: ex1
#      sampler: samp1
#      runner: runner1