logging: INFO

executors:
  e1:
    type: DaskExecutor
    SLURMcluster_config:
      account: "project_2009007"
      queue: "small"
      cores: 1 
      memory: "1GB"
      processes: 1
      walltime: "00:05:00"
      interface: "ib0"
      job_name: enchanted-surrogates-example
    scale_n_jobs: 1
samplers:
  s1:
    type: RandomSampler
    bounds: [[0.0, 1.0], [0.0, 10.0]]
    budget: 4
    parameters: ['c1', 'c2']
runners:
  r1:
    type: ExampleRunner
    other_params: {}

supervisor:
  base_run_dir: "data_dir/dask_slurm"
  local_storage: TMPDIR
  run_order:
  - executor: e1
    sampler: s1
    runner: r1

storage:
  type: hdf5
