sampler:
  type: RandSampler
  bounds: [[0.08, 0.47], [0.015, 0.055], [0.8, 10.2], [0.8,3.2], [1,4.0], [0.25, 0.65]]
  num_samples: 1000
  parameters: ['tria', 'pedestal_delta', 'n_eped', 'bvac', 'ip', 'teped_multip']

runner:
  type: HELENArunner
  executable_path: "/scratch/project_2009007/HELENA/bin/hel13_64"
  other_params: {
    "namelist_path": "/scratch/project_2009007/ench-surr-helper/helena/fort.10",
    "input_parameter_type": 1, 
    "only_generate_files": False,
    "mishka": {
      "run_mishka": True,
      "executable_path": "/scratch/project_2009007/MISHKA/bin/mishka/mishka1fast_gfortran",
      "ntor": [5,7,10,15,20,30,50],
      "other_params": {
        "namelist_path": "/scratch/project_2009007/ench-surr-helper/mishka/fort.10",
        "input_fort12": "",
        "input_density": "",
      }
    }
  }

executor:
  type: DaskExecutor
  base_run_dir: /scratch/project_2009007/data_HELENA/random_samples_2024-06-27
  worker_args: # to be specified for the SLURMCluster in DASK
    account: "project_2009007"
    queue: "medium"
    cores: 1 
    memory: "12GB"
    processes: 1
    walltime: "10:00:00" # Adam: survival length of worker, so possibly just set to max in cluster
    interface: "ib0"
    job_script_prologue: # this is possibly dependent on which code you want
      - 'module load python-data'
      - 'cd /scratch/project_2009007/enchanted-surrogates'
      - 'export PYTHONPATH=$PYTHONPATH:/scratch/project_2009007/enchanted-surrogates/src' # NB: to use the enchanted-surrogate library
    # n_workers: 1  # a single job may include one or more workers
  n_jobs: 20