sampler:
  type: Grid
  bounds: [[1.8, 10], [0.001, 0.4]]
  num_samples: [2, 2]
  parameters: ['alpha_T1', 'width_pressure_alpha']

runner:
  type: HELENArunner
  executable_path: "/scratch/project_2009007/HELENA/bin/hel13_64"
  other_params: {
    "namelist_path": "/scratch/project_2009007/ench-surr-helper/helena/fort.10",
    "only_generate_files": False}

executor:
  type: DaskExecutor
  base_run_dir: /scratch/project_2009007/test-enchanted/helena
  worker_args: # to be specified for the SLURMCluster in DASK
    account: "project_2009007"
    queue: "medium"
    cores: 1 
    memory: "12GB"
    processes: 1
    walltime: "00:10:00" # Adam: survival length of worker, so possibly just set to max in cluster
    interface: "ib0"
    job_script_prologue: # this is possibly dependent on which code you want
      - 'module load python-data'
      # - 'cd /scratch/project_2009007/enchanted-surrogates'
      - 'export PYTHONPATH=$PYTHONPATH:/scratch/project_2009007/enchanted-surrogates/src' # NB: to use the enchanted-surrogate library
      - 'cd /scratch/project_2009007/enchanted-surrogates'
      # - 'cd /scratch/project_2007159/cursed-tglf/'
      # - 'export PYTHONPATH=$PYTHONPATH:/scratch/project_2007159/cursed-tglf/src' # NB: to use the enchanted-surrogate library
  n_jobs: 2