sampler:
  type: Grid
  bounds: [[0.1, 0.5], [0.01, 0.05], [0.5, 0.9], [1, 10]]
  num_samples: 3
  parameters: ['tria', 'pedestal_delta', 'n_esep', 'n_eped']

runner:
  type: HELENArunner
  executable_path: "/scratch/project_2009007/HELENA/bin/hel13_64"
  other_params: {
    "namelist_path": "/scratch/project_2009007/europed_rewrite/helena_width_scans_240308124851248459/0/fort.10",
    "only_generate_files": True}

executor:
  type: LocalDaskExecutor
  base_run_dir: /scratch/project_2009007/test-enchanted/helena_2024-03-25
  worker_args: # to be specified for the SLURMCluster in DASK
    account: "project_2009007"
    queue: "medium"
    cores: 1 
    memory: "12GB"
    processes: 1
    walltime: "00:20:00" # Adam: survival length of worker, so possibly just set to max in cluster
    interface: "ib0"
    job_script_prologue: # this is possibly dependent on which code you want
      - 'module load python-data'
      - 'cd /scratch/project_2009007/enchanted-surrogates'
      - 'export PYTHONPATH=$PYTHONPATH:/scratch/project_2009007/enchanted-surrogates/src' # NB: to use the enchanted-surrogate library
  num_workers: 3