sampler:
  type: Grid
  bounds: [[1, 3], [1, 3]]
  num_samples: 3
  parameters: ['m', 'n']

runner:
  type: SIMPLErunner
  executable_path: /scratch/project_2009007/enchanted-surrogates/tests/simple/simple.sh
  other_params: {}

executor:
  type: DaskExecutor
  base_run_dir: /scratch/project_2009007/test-enchanted/trial_dask
  worker_args: # to be specified for the SLURMCluster in DASK
    local: 1
    account: "project_2009007"
    queue: "medium"
    cores: 2 
    memory: "1GB"
    processes: 1
    walltime: "00:10:00" # Adam: survival length of worker, so possibly just set to max in cluster
    interface: "ib0"
    job_script_prologue: # this is possibly dependent on which code you want
      - 'module load python-data'
      - 'cd /scratch/project_2009007/enchanted-surrogates/'
      - 'export PYTHONPATH=$PYTHONPATH:/scratch/project_2009007/enchanted-surrogates/src' # NB: to use the enchanted-surrogate library
    n_workers: 2