sampler:
  type: Grid
  bounds: [[1, 3], [1, 3]]
  num_samples: 3
  parameters: ['m', 'n']

executor:
  type: DaskExecutorSimulationPipeline
  executor_simulation:
    type: DaskExecutorSimulation
    #A runner can only use one resource configuration. 
    runner:
      type: SIMPLErunner
      executable_path: /scratch/project_2009007/enchanted-surrogates/tests/simple/simple.sh
      other_params: {}
      base_run_dir: /scratch/project_2009007/test-enchanted/trial_dask
      # Each runner only has one parser and so this is defined in the runner itself
    # Resources needed for 1 run of the runner, except walltime this is the survival time of the whole cluster.
    worker_args: # to be specified for the SLURMCluster in DASK
      local: 1
      account: "project_2009007"
      queue: "medium"
      cores: 2 
      memory: "1GB"
      processes: 1
      walltime: "00:10:00" # Adam: survival length of worker, so possibly just set to max in cluster
      interface: "ib0"
      job_script_prologue: # this is possibly dependent on which code you want
        - 'module load python-data'
        - 'cd /scratch/project_2009007/enchanted-surrogates/'
        - 'export PYTHONPATH=$PYTHONPATH:/scratch/project_2009007/enchanted-surrogates/src' # NB: to use the enchanted-surrogate library
    n_jobs: 2 #Number of slurm jobs, each slurm job is one worker. 

  parser:
    type: SimplePipelineParser
    function: simple_out_to_simple_in

  executor_simulation:
    type: DaskExecutorSimulation
    runner:
      type: SIMPLErunner
      executable_path: /scratch/project_2009007/enchanted-surrogates/tests/simple/simple.sh
      other_params: {}
      base_run_dir: /scratch/project_2009007/test-enchanted/trial_dask
      # Each runner only has one parser and so this is defined in the runner itself
    base_run_dir: /scratch/project_2009007/test-enchanted/trial_dask
    worker_args: # to be specified for the SLURMCluster in DASK
      local: 1
      account: "project_2009007"
      queue: "medium"
      cores: 2 
      memory: "1GB"
      processes: 1
      walltime: "00:10:00" # Adam: survival length of worker, so possibly just set to max in cluster
      interface: "ib0"
      job_script_prologue: # this is possibly dependent on which code you want
        - 'module load python-data'
        - 'cd /scratch/project_2009007/enchanted-surrogates/'
        - 'export PYTHONPATH=$PYTHONPATH:/scratch/project_2009007/enchanted-surrogates/src' # NB: to use the enchanted-surrogate library
    n_jobs: 2