sampler:
  type: Grid
  bounds: [[1, 3], [1, 3]]
  num_samples: 3
  parameters: ['m', 'n']

runner:
  type: SIMPLErunner
  executable_path: /project/project_462000451/enchanted-surrogates/tests/simple/simple.sh
  other_params: {}

executor:
  type: DaskExecutor
  base_run_dir: /project/project_462000451/test-enchanted/trial-dask
  output_dir: /scratch/project_462000451/gene_out/enchanted_out/simple_test
  worker_args: # to be specified for the SLURMCluster in DASK
    account: "project_462000451"
    queue: "small"
    cores: 2 # Total number of cores to be split amongst the workers
    memory: "4GB"
    walltime: "00:10:00" # Adam: survival length of worker, so possibly just set to max in cluster
    interface: "nmn0"
    job_script_prologue: # this is possibly dependent on which code you want
      - 'export PATH="/project/project_462000451/enchanted_container_lumi3/bin:$PATH"'
      - 'cd /project/project_462000451/enchanted-surrogates/'
      - 'export PYTHONPATH=$PYTHONPATH:/project/project_462000451/enchanted-surrogates/src' # NB: to use the enchanted-surrogate library
    n_workers: 2
  n_jobs: 1
  