sampler:
  type: HypercubeSampler
  bounds: [[0, 1], [0, 1]]
  num_samples: 128
  parameters: ['alpha', 'beta']

runner:
  type: TGLFrunner
  executable_path: "/path/to/simulation/executable"
  other_params: {}

executor:
  type: DaskExecutor
  base_run_dir: /scratch/project_2007159/cursed-tglf/trial_dask
  num_workers: 5
  worker_args: # to be specified for the SLURMCluster in DASK
    account: "project_2005083"
    queue: "medium"
    cores: 1 
    memory: "12GB"
    processes: 1
    walltime: "00:10:00" # Adam: survival length of worker, so possibly just set to max in cluster
    interface: "ib0"
    job_script_prologue: # this is possibly dependent on which code you want
      - 'module load python-data'
      - 'cd /scratch/project_2007159/cursed-tglf/'
      - 'export PYTHONPATH=$PYTHONPATH:/scratch/project_2007159/cursed-tglf/src' # NB: to use the enchanted-surrogate library
      - 'export GACODE_ROOT=/scratch/project_2007159/cursed-tglf/gacode' # TODO: these are for sure tglf specific
      - 'export GACODE_PLATFORM=MAHTI'
      - '. $GACODE_ROOT/shared/bin/gacode_setup'
      - '. $GACODE_ROOT/platform/env/env.$GACODE_PLATFORM'