# sampler/grid.py

# from .base import Sampler
from itertools import product
import numpy as np
import importlib
from enchanted_surrogates.utils.precise_imports import import_sampler
from enchanted_surrogates.samplers.base_sampler import Sampler


class NestedSampler(Sampler):
    """
    ---

    ## Overview
    `NestedSampler` composes multiple samplers into a single sampler by
    generating the Cartesian product of their initial sample sets.

    Each nested sampler is initialized independently, and all combinations
    of their initial samples are merged into joint parameter configurations.
    The sampler produces exactly one batch of samples and does not support
    iterative or adaptive sampling.

    ---

    ## Configuration

    The `NestedSampler` is configured by specifying a dictionary of sub-samplers,
    each with its own type and configuration.

    Example configuration:

    ```yaml
    sampler:
      type: NestedSampler
      samplers:
        sampler_a:
          type: GridSampler
          parameters: ['x']
          bounds: [[0, 1]]
          num_samples: [4, 3]

        sampler_b:
          type: RandomSampler
          parameters: ['y', 'z']
          bounds: [[0, 1], [10, 20]]
          num_samples: 2

      budget: 24
    ```
    In this example:

      - `sampler_a` generates 12 samples for `(x)`

      - `sampler_b` generates 2 samples for `(y, z)`

      - The nested sampler produces `12 × 2 = 24` combined configurations.


    ---
    
    Args:
        samplers(dict): Dictionary defining the nested samplers.
        type(S): Sampler class name, sampler-specific configuration parameters
        budget (int): Maximum number of combined samples. Currently used for bookkeeping only.
        batch_size (int): Number of samples returned in a single batch. Defaults to `budget`.
    
    ---

    ## Assumptions and notes

    - Each nested sampler must implement `get_next_samples()` and expose a `parameters` attribute.
    - All samples are generated eagerly during initialization.
    - The total number of generated samples grows multiplicatively with the number of nested samplers.

    ---

    ## Methods

      **`__init__:`** Initializes all nested samplers and generates initial samples.

      **`get_next_samples:`** Returns the Cartesian product of nested samples.
    
    ---

    """

    def __init__(self, samplers, *args, **kwargs):

        """
        **`__init__:`** Initializes the NestedSampler and all nested samplers.

        Each nested sampler is instantiated using its provided configuration,
        and its initial samples are collected immediately. The full Cartesian
        product of these samples defines the nested search space.

        """
        samplers_keys = samplers.keys
        samplers_types = [samplers[k]['type'] for k in samplers_keys()]
        samplers_config = [samplers[k] for k in samplers_keys()]
        self.all_samplers = [import_sampler(sampler_type, sampler_config) for sampler_type, sampler_config in zip(samplers_types, samplers_config)]
        self.budget = kwargs.get('budget')
        self.batch_size = kwargs.get('batch_size', self.budget)
        self.submitted = 0
        self.all_parameters = [param for sampler in self.all_samplers for param in sampler.parameters]

        self.initial_parameters = []
        for sampler in self.all_samplers:
            self.initial_parameters.append(sampler.get_next_samples())

        self.total_num_runs = [np.sum(np.cumprod([len(ip) for ip in self.initial_parameters]))]
        self.depth_num_runs = [np.cumprod([len(ip) for ip in self.initial_parameters])]
        self.current_batch = 0 
    def get_next_samples(self):

        """
        Returns the combined parameter configurations generated by the nested samplers.

        On the first call, this method computes the Cartesian product of the initial samples from all nested samplers and merges their parameter
        dictionaries into joint configurations.

        Returns:
            list[dict]:
              A list of combined parameter dictionaries.

        Raises:
            NotImplementedError:
              If called more than once.

        """

        if self.current_batch == 0:
            # get all initial parameters
            
            # Cartesian product of all sublists
            combinations = product(*self.initial_parameters)
            # Merge each tuple of dicts into a single dict
            combined = [dict(kv for d in combo for kv in d.items()) for combo in combinations]
            
            self.submitted += len(combined)
            # self.has_budget = False # nested sampler only supports one batch. For nested active sampling a bespoke nested sampler is needed for each application
            self.current_batch += 1
            return combined
        else:
            raise NotImplementedError
    
    def register_future(self, future):
        """
        Registers a completed or scheduled evaluation.

        This method is part of the sampler interface but is not used by the
        NestedSampler, as it does not adapt based on evaluation results.

        Args:
            future:
              A future or handle representing an asynchronous evaluation.

        Returns:
            None
        """
        return None

    def register_futures(self, futures):
        """
        Registers multiple completed or scheduled evaluations.

        This method is part of the sampler interface but is implemented as
        a no-op for the NestedSampler.

        Args:
            futures:
              An iterable of futures or handles representing evaluations.

        Returns:
            None
        """

        return None
