name: Automated documentation using mkdocs

on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'bug/**'
      - 'dev**'

  pull_request:
    types: [opened, reopened]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: |
          pip install mkdocs mkdocstrings[python] mkdocs-material

      - run: mkdocs build

      - uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - uses: actions/deploy-pages@v4

