name: Automated documentation using mkdocs

on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Restore cached virtualenv
        uses: actions/cache/restore@v5
        with:
          key: venv-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('pyproject.toml') }}
          path: .venv

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install h5py
          pip install mkdocs mkdocstrings[python] mkdocs-material pymdown-extensions mkdocs-gen-files
          pip install -e .

      - name: Checkout private docs from plugin Mishka
        uses: actions/checkout@v6
        with:
          repository: DIGIfusion/enchanted-plugin-mishka
          token: ${{ secrets.MISHKA_TOKEN }}
          path: plugins_docs/mishka_plugin

      - name: Add private plugin to PYTHONPATH
        run: |
          source .venv/bin/activate
          echo "PYTHONPATH=$(pwd)/plugins_docs/mishka_plugin/src" >> $GITHUB_ENV

      - name: Build MkDocs site
        run: |
          source .venv/bin/activate
          mkdocs build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Saved cached virtualenv
        uses: actions/cache/save@v5
        with:
          key: venv-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('pyproject.toml') }}
          path: .venv

  deploy:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
