name: Automated documentation using mkdocs

on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install \
            mkdocs==1.6.1 \
            mkdocs-material==9.7.6 \
            mkdocs-autorefs==1.4.4 \
            mkdocs-gen-files==0.6.1 \
            mkdocs-get-deps==0.2.2 \
            mkdocs-material-extensions==1.3.1 \
            mkdocstrings==1.0.3 \
            mkdocstrings-python==2.0.3 \
            markdown==3.10.2 \
            pymdown-extensions==10.21 \
            jinja2==3.1.6 \
            pygments==2.19.2 \
            pyyaml==6.0.3 \
            h5py==3.16.0
          pip install -e .

      - name: Checkout plugins from config
        env:
          GH_PAT: ${{ secrets.PLUGINS_TOKEN }}
        run: python docs/scripts/checkout_plugins.py
  
      - name: Set PYTHONPATH
        run: |
           PY_PATH=""
           for dir in plugins/*; do
             PY_PATH="$PY_PATH:$(pwd)/$dir/src"
           done
           echo "PYTHONPATH=$PY_PATH" >> $GITHUB_ENV

      - name: Generate plugin docs
        run: python docs/scripts/generate_plugin_docs.py    

      - name: Build MkDocs site
        run: mkdocs build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
