name: Python linting with ruff

on: 
  workflow_call:
  push:
    branches:
      - main
      - 'feature/**'
      - 'bug/**'
      - 'dev**'
  pull_request:
    types: [opened, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      # working-directory: enchanted_surrogates
      run: |
        python -m pip install --upgrade pip
        pip install -e . 
    - name: Analysing the code with ruff
      # working-directory: enchanted_surrogates
      run: |
        ruff check $(git ls-files '*.py')
