name: Python linting with ruff

on: 
  workflow_call:
  push:
    branches:
      - main
      - 'feature/**'
      - 'bug/**'
      - 'dev**'
  pull_request:
    types: [opened, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v6

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Restore cached virtualenv
      uses: actions/cache/restore@v5
      with:
        key: venv-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('pyproject.toml') }}
        path: .venv

    - name: Install dependencies
      # working-directory: enchanted_surrogates
      run: |
        if [ ! -d ".venv" ]; then
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -e . 
        fi
    - name: Analysing the code with ruff
      # working-directory: enchanted_surrogates
      run: |
        source .venv/bin/activate
        ruff check $(git ls-files '*.py')

