name: Unit testing with Pytest

on: 
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    types: [opened, reopened]
jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        git submodule init
        git submodule update
    - name: Running pytest
      run: |
        coverage run -m pytest tests/test_grid.py -v -s
        coverage run -m pytest tests/test_random.py -v -s
        coverage run -m pytest tests/test_simple.py -v -s
    - name: Generate Coverage Report  
      run: |  
        coverage report -m