name: Unit testing with Pytest

on: 
  workflow_call:
  # push:
  #   branches: [main, develop]
  # pull_request:
  #   types: [opened, synchronize, reopened]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v6

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}


    - name: Restore cached virtualenv
      uses: actions/cache/restore@v5
      with:
        key: venv-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('pyproject.toml') }}
        path: .venv


    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        python -m pip install --upgrade pip
        pip install -e ".[activelearning]" # Editable install, required for importlib to do precise imports
        pip install coverage
        git submodule init
        git submodule update

    - name: Running pytest
      run: |
        coverage run --source=src --data-file=.coverage.unit -m pytest tests/ -v -s

    - name: Upload coverage artifacts
      uses: actions/upload-artifact@v7
      with:
        name: unit_coverage
        include-hidden-files: true
        path: |
          .coverage.unit


    - name: Saved cached virtualenv
      uses: actions/cache/save@v5
      with:
        key: venv-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('pyproject.toml') }}
        path: .venv

