name: Unit testing with Pytest

on: 
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    types: [opened, reopened]
jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{secrets.DANIEL_TOKEN}}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: | 
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        git -c http.extraheader="AUTHORIZATION: Bearer ${{ secrets.DANIEL_TOKEN }}" submodule init
        git -c http.extraheader="AUTHORIZATION: Bearer ${{ secrets.DANIEL_TOKEN }}" submodule init submodule update
    - name: Running pytest
      run: |
        coverage run -m pytest tests/automated_tests_no_HPC -v -s        
    - name: Generate Coverage Report  
      run: |  
        coverage report -m