name: Automated testing

on: 
  workflow_call:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  unit_tests:
    uses: ./.github/workflows/pytest.yml

  workflow_tests:
    uses: ./.github/workflows/pytest_workflow.yml

  combine_coverage:
    needs: [unit_tests, workflow_tests]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage

    - name: Download unit test coverage
      uses: actions/download-artifact@v4
      with:
        name: unit_coverage
        path: coverage

    - name: Download workflow test coverage
      uses: actions/download-artifact@v4
      with:
        name: workflow_coverage
        path: coverage

    - name: Combine and generate coverage report
      run: |
        ls coverage
        coverage combine coverage
        coverage report -m > coverage_by_file.txt
        coverage xml

    - name: Upload coverage artifacts
      uses: actions/upload-artifact@v4
      with:
        name: combined_coverage
        path: |
          coverage_by_file.txt
          coverage.xml
    
  coverage:
    needs: combine_coverage
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/coverage_report.yml
